kind: pipeline
type: docker
name: test


steps:
  - name: build
    # 默认为最新版镜像
    image: rust
    volumes:
      - name: rust_source
        path: ~/.cargo/config
    commands:
      - cargo build


volumes:
  - name: rust_source
    host:
      path: /home/devops/drone/rust/config
